# Generated by Django 3.0.7 on 2020-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=50)),
                ('module', models.CharField(default='', max_length=50)),
                ('function', models.CharField(default='', max_length=50)),
                ('filename', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_entries',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExtendedLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=50)),
                ('module', models.CharField(default='', max_length=50)),
                ('function', models.CharField(default='', max_length=50)),
                ('filename', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('special', models.CharField(default='', max_length=50)),
                ('user', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'extended_log_entries',
                'default_permissions': (),
            },
        ),
    ]
